### PR TITLE
upgrade to go-ipld-prime v0.10

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by mvdan** [comment]
Hold off on merging for now, as per https://github.com/ipld/go-ipld-adl-hamt/issues/22#issuecomment-881652760.

**Review by willscott — APPROVED** [review]

**Review by warpfork — APPROVED** [review]
:+1: :tada: :heart: :rocket:

**Comment by mvdan** [comment]
I had actually forgotten to re-run the code generator, @marten-seemann thanks for the reminder.

I'm thinking we can probably merge this, since AFAIK noone is using this ADL right now, and they could always pin the current master commit. Not that I'm in a rush, but I can't fix https://github.com/ipld/go-ipld-adl-hamt/issues/25#issuecomment-884502304 without LinkSystem, so I'd have to keep piling commits on this PR.

**Comment by willscott** [comment]
Yeah. Agree that merge is the right call here.

**Comment by marten-seemann** [comment]
> I had actually forgotten to re-run the code generator, @marten-seemann thanks for the reminder.

Another use case for the `go-generate` workflow. Maybe it's time to fix https://github.com/protocol/.github/issues/123 (make it opt-in for repos), and activate it everywhere go-ipld-prime code generation is used?

**Pull request merged**
